added 'org.springframework.integration:spring-integration-jmx' - breaks build
no longer builds. error:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed
to instantiate
[org.springframework.messaging.support.AbstractSubscribableChannel]:
Factory method 'brokerChannel' threw exception; nested exception is
java.lang.ClassCastException: com.sun.proxy.$Proxy66 cannot be cast to
org.springframework.messaging.support.AbstractSubscribableChannel
	at
org.springframework.beans.factory.support.ConstructorResolver.instantiat
eUsingFactoryMethod(ConstructorResolver.java:599)
	at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFac
tory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.ja
va:1111)
	at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFac
tory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1006)
	at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFac
tory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFac
tory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at
org.springframework.beans.factory.support.AbstractBeanFactory$1.getObjec
t(AbstractBeanFactory.java:303)
	at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.g
etSingleton(DefaultSingletonBeanRegistry.java:230)
	at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(
AbstractBeanFactory.9)va:29
	at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(Ab
stractBeanFactory.java:194)
	at
org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMe
thodInterceptor.intercept(ConfigurationClassEnhancer.java:322)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.brokerChannel(<g
enerated>)
	at
org.springframework.messaging.simp.config.AbstractMessageBrokerConfigura
tion.brokerMessagingTemplate(AbstractMessageBrokerConfiguration.java:275
)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.CGLIB$brokerMess
agingTemplate$29(<generated>)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3$$FastClassBySpri
ngCGLIB$$97020410.invoke(<generated>)
	at
org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java
:228)
	at
org.springframework.beans.factory.support.SimpleInstantiationStrategy.in
stantiate(SimpleInstantiationStrategy.java:189)
	at
org.springframework.beans.factory.support.ConstructorResolver.instantiat
eUsingFactoryMethod(ConstructorResolver.java:588)
	... 52 more
Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy66 cannot
be cast to
org.springframework.messaging.support.AbstractSubscribableChannel
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.clientInboundCha
nnel(<generated>)
	at
org.springframework.messaging.simp.config.AbstractMessageBrokerConfigura
tion.getBrokerRegistry(AbstractMessageBrokerConfiguration.java:212)
	at
org.springframework.messaging.simp.config.AbstractMessageBrokerConfigurr
okerChannel(AbstractMessageBrokerConfiguration.java:180)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.CGLIB$brokerChan
nel$24(<generated>)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3$$FastClassBySpri
ngCGLIB$$97020410.invoke(<generated>)
	at
org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java
:228)
	at
org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMe
thodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.brokerChannel(<g
enerated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.jav
a:62)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessor
Impl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at
org.springframework.beans.factory.support.SimpleInstantiationStrategy.in
stantiate(SimpleInstantiationStrategy.java:162)
	... 53 more
	at
org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMe
thodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.brokerMessagingT
emplate(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.jav
a:62)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessor
Impl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at
org.springframework.beans.factory.support.SimpleInstantiationStrategy.in
stantiate(SimpleInstantiationStrategy.java:162)
	... 31 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed
to instantiate
[org.springframework.messaging.support.AbstractSubscribableChannel]:
Factory method 'brokerChannel' threw exception; nested exception is
java.lang.ClassCastException: com.sun.proxy.$Proxy66 cannot be cast to
o
rg.springframework.messaging.support.AbstractSubscribableChannel
	at
org.springframework.beans.factory.support.SimpleInstantiationStrategy.in
stantiate(SimpleInstantiationStrategy.java:189)
	at
org.springframework.beans.factory.support.ConstructorResolver.instantiat
eUsingFactoryMethod(ConstructorResolver.java:588)
	... 52 common frames omitted
Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy66 cannot
be cast to
org.springframework.messaging.support.AbstractSubscribableChannel
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.clientInboundCha
nnel(<generated>)
	at
org.springframework.messaging.simp.config.AbstractMessageBrokerConfigura
tion.getBrokerRegistry(AbstractMessageBrokerConfiguration.java:212)
	at
org.springframework.messaging.simp.config.AbstractMessageBrokerConfigura
tion.brokerChannel(AbstractMessageBrokerConfiguration.java:180)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.CGLIB$brokerChan
nel$24(<generated>)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3$$FastClassBySpri
ngCGLIB$$97020410.invoke(<generated>)
	at
org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java
:228)
	at
org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMe
thodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at
org.springframework.web.socket.config.annotation.DelegatingWebSocketMess
ageBrokerConfiguration$$EnhancerBySpringCGLIB$$1d9c90b3.brokerChannel(<g
enerated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.jav
a:62)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessor
Impl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at
org.springframework.beans.factory.support.SimpleInstantiationStrategy.ia
te(SimpleInstantiationStrategy.java:162)
	... 53 common frames omitted
```